<template>
  <!-- table -->
  <section class="row">
    <div class="col-12">
      <table
        class="table table-bordered table-hover table-striped table-sm table-dark text-center mt-3"
      >
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">X</th>
            <th scope="col">Y</th>
            <th scope="col">Z</th>
          </tr>
        </thead>
        <tbody>
          <tr
            v-show="points.length > 0"
            v-for="po in points"
            :key="po.pn"
            @dblclick="setSelectedPoint(po)"
            class="point-tr user-select-none"
            :class="selectedPoint.pn === po.pn ? 'selected-tr' : ''"
          >
            <th scope="row">{{ po.pn }}</th>
            <td>{{ po.x }}</td>
            <td>{{ po.y }}</td>
            <td>{{ po.z }}</td>
          </tr>
          <tr v-show="points.length === 0">
            <td colspan="4" class="text-muted user-select-none">No points</td>
          </tr>
        </tbody>
      </table>
    </div>
  </section>
</template>

<script>
export default {
  name: "CoordinatesTable",
  props: {
    points: {
      type: Array,
    },
    selectedPoint: {
      type: Object,
    },
    setSelectedPoint: {
      type: Function,
    },
  },
};
</script>

<style scoped>
.point-tr {
  cursor: pointer;
}
.selected-tr {
  outline: aqua 1px dashed;
}

.scale-up-center {
  -webkit-animation: scale-up-center 0.4s cubic-bezier(0.39, 0.575, 0.565, 1)
    both;
  animation: scale-up-center 0.4s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2022-10-18 9:38:51
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-center
 * ----------------------------------------
 */
@-webkit-keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}
@keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}
</style>
